# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_articlefavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumb/default.jpg', null=True, upload_to='thumb'),
        ),
    ]
