# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180525_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='审核通过'),
        ),
    ]
